### ISSUE TITLE
WARNING level logging on every use

### ISSUE THREAD

**Issue by vinceatbluelabs** [exhuma/config_resolver#69]
I'm looking to integrate config_resolver in https://github.com/bluelabsio/records-mover.  This is exactly the library I was looking for to provide flexible configuration--thanks for writing it!!

In records-mover, I use Python standard logging.  Unfortunately, it appears that every time I use `get_config()`, I get quite a bit of logging at a very high level (`WARNING`): 

```
group=bluelabs:app=records_mover:Skipping unreadable file /etc/bluelabs/records_mover/app.ini (File not found)
group=bluelabs:app=records_mover:Skipping unreadable file /etc/xdg/bluelabs/records_mover/app.ini (File not found)
group=bluelabs:app=records_mover:Skipping unreadable file /Users/broz/.config/bluelabs/records_mover/app.ini (File not found)
```

This appears to be coming from here:

https://github.com/exhuma/config_resolver/blob/7fab236a9b9a51b2517264f089ee57688890c64d/config_resolver/core.py#L189

Would you accept a PR to change this log level to DEBUG?  It seems to me the idea of not having every potential config location full is not a concerning condition that should be warned about.  

The workaround I have now is essentially to turn off logging altogether (`logging.getLogger('config_resolver').setLevel(logging.ERROR)`), but that would also suppress any potential concerning issues at WARNING or useful progress information at INFO being logged by `config_resolver`.

**Comment by exhuma** [comment]
Yeah sure. You can throw a PR my way for this. I initially gave these messages a fairly high severity because I thought it would help to spot potential errors. But, after dogfooding myself on this library for several years now, I actually rely more on the `require_load` flag than on the logging itself.

Alternatively you can have a look at [this filter I wrote](https://github.com/exhuma/gouge/blob/master/gouge/filters.py#L9). It is part of my own little logging helper package [gouge](https://github.com/exhuma/gouge). Unfortunately I just noticed that the API docs are borked, but the libarary is tiny and reading the docstrings in the code should be doable 😉

I had the same issue with some libraries being a bit aggressive with logging levels, giving me the exact same situation as you are in with my library now 😉 Using the linked filter gives you a bit more control. I hope my docstrings are understandable. Essentially the filter changes the log level of every message in the given logger hierarchy by *n* levels. So with a "shift" of `1` would modify the levels as follows:

Original Level | Shifted by 1 | Shifted by 2
------------ | ------------- | -----------
CRITICAL | ERROR | WARNING
ERROR | WARNING | INFO
WARNING | INFO | DEBUG
INFO | DEBUG | DEBUG
DEBUG | DEBUG | DEBUG

The filter gives a bit more flexibility. If you have questions feel free to ask.

**Comment by vinceatbluelabs** [comment]
Thanks!  I opened a PR.  I like the filtering approach, though - thankfully this is the first time I've hit this in Python.

**Comment by vinceatbluelabs** [comment]
Hi @exhuma!  Mind checking out my PR?  https://github.com/exhuma/config_resolver/pull/70

**Comment by exhuma** [comment]
Sorry for the delay, I was a bit distracted the past week with some personal stuff. I'm looking into it right now.

**Comment by exhuma** [comment]
Has been release as 5.0.1

**Comment by vinceatbluelabs** [comment]
Thanks so much!  It's working like a champ.
